-- AlterEnum
ALTER TYPE "ServiceType" ADD VALUE 'CURVED_CUTTING';
ALTER TYPE "ServiceType" ADD VALUE 'CURVED_POLISHING';
ALTER TYPE "ServiceType" ADD VALUE 'RADIUS_SETUP';
ALTER TYPE "ServiceType" ADD VALUE 'CURVED_MIN_LM';
